### ISSUE TITLE
swift 2.0

### ISSUE THREAD

**Issue by longxianlin** [Gasimzada/FxDatePicker#1]
``
init() {
            self.calendar = NSCalendar.currentCalendar();
            self.components = NSDateComponents();
        }

```
    init(calendar : NSCalendar, order : [String : Int]) {
        self.calendar = calendar
        self.components = calendar.components([.Year, .Month, .Day, .Hour, .Minute, .Minute], fromDate: NSDate())
        self.order = order;
    }
```

/*
    override init() {
        super.init();
        initialize();
        self.frame = CGRect(x: 0, y: 0, width: 420, height: 216);
    }*/

```
```

**Comment by GasimGasimzada** [comment]
Please make a pull request and I will accept it.

**Comment by GasimGasimzada** [comment]
Swift 2.0 support added. I will keep working on the features because you have shown interest in my project. Thank you for the feedback!
